import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex min-h-screen flex-col">
          <div className="flex-1">{children}</div>
          {/* <footer className="mt-12 h-72 bg-secondary" /> */}
        </main>
        <Toaster position="top-center" expand theme="light" richColors duration={2000} />
      </body>
    </html>
  );
}
